apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    basicAuth: false
    isDefault: false
    database: ovs_metrics
    user: admin
    jsonData:
      httpMode: GET
    secureJsonData:
      password: admin
    editable: true